services:
  - type: web
    name: krapto-load-balancer
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: PORT
        value: 80
    healthCheckPath: /health
    autoDeploy: true